### PR TITLE
 fix: #27 translation of English to Hindi file added in i18n folder

### PR DESCRIPTION
**Pull request by dnyaneshwar-rede**
fix: #27 
wallet Address :
SEKReW5GbzQKY6uAYyo4CB4nwcWEnBp7bYjUn6K3RdrFbhMBpFWVHndQenGA2bT7BM1UVSCYu46jEf6afxyrrCKTb6P38hz8t1M

### CODE REVIEW

**Comment by dnyaneshwar-rede** [comment]
@f-r00t Any Update sir , I have done Transalation in Hindi

**Comment by f-r00t** [comment]
Thanks, buddy!

Tx hash: 8557fdaa79ecb90e88adcd48402caf46a6545bf600240b548bc0bd759655004f

**Comment by dnyaneshwar-rede** [comment]
Actually I don't received yet bounty

**Comment by f-r00t** [comment]
You're connected to an offline node, please change it in settings. Here's a list of public nodes: https://explorer.kryptokrona.se/nodes.html

**Pull request merged**
